sudo: false

env:
  matrix:
  - PYTHON_VERSION: 2.7
  - PYTHON_VERSION: 3.4

script:
- python condaci.py setup

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
